Vipa\EndorsementBundle\Entity\Skill:
  repositoryClass: Vipa\EndorsementBundle\Entity\SkillRepository
  table: en_skill
  type: entity
  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false
    loggable: true
  id:
    id:
      generator:
        strategy: AUTO
      id: true
      type: integer
  fields:
    name:
      type: string
      nullable: false
    created:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create
    updated:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update
    deletedAt:
      type: date
      nullable: true
    createdBy:
      type: string
      nullable: true
      gedmo:
        blameable:
          on: create
    updatedBy:
      type: string
      nullable: true
      gedmo:
        blameable:
          on: update
  lifecycleCallbacks: {}
