Vipa\EndorsementBundle\Entity\UserSkill:
  type: entity
  table: en_user_skill
  repositoryClass: Vipa\EndorsementBundle\Entity\UserSkillRepository
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  uniqueConstraints:
      user_skill_idx:
          columns: user_id, skill_id
  fields:
    endorsementCount:
      column: endorsement_count
      type: integer
  manyToOne:
    user:
      targetEntity: Vipa\UserBundle\Entity\User
      joinColumn:
        name: user_id
        referencedColumnName: id
    skill:
      targetEntity: Vipa\EndorsementBundle\Entity\Skill
      joinColumn:
        name: skill_id
        referencedColumnName: id
  oneToMany:
    userSkillEndorsers:
      targetEntity: Vipa\EndorsementBundle\Entity\UserEndorse
      mappedBy: userSkill
      cascade: ["persist", "remove"]
