Vipa\EndorsementBundle\Entity\UserEndorse:
  type: entity
  table: en_user_endorse
  repositoryClass: Vipa\EndorsementBundle\Entity\UserSkillRepository
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  uniqueConstraints:
      user_skill_endorser_idx:
          columns: user_skill_id, endorser_id
  fields:
  manyToOne:
    userSkill:
      targetEntity: Vipa\EndorsementBundle\Entity\UserSkill
      joinColumn:
        name: user_skill_id
        referencedColumnName: id
    endorser:
      targetEntity: Vipa\UserBundle\Entity\User
      joinColumn:
        name: endorser_id
        referencedColumnName: id
