services:
  endorsement.endorsement_event_listener:
    class: Vipa\EndorsementBundle\EventListener\EndorsementEventListener
    arguments: ["@doctrine.orm.entity_manager", "@router", "@vipa.journal_service", "@security.token_storage", "@twig", '@translator']
    tags:
      - { name: kernel.event_subscriber }
